### ISSUE TITLE
Only first subdomain is used when querying consul

### ISSUE THREAD

**Issue by shawnsi** [vlipco/srv-router#4]
Is there a reason behind this [replacement](https://github.com/vlipco/srv-router/blob/master/conf/srv_router.lua#L35)?  I'd like to use URLs like ``tag.service.127.0.0.1.xip.io`` to select different environments for a single service.  The string.gsub linked above removes the tag subdomain unfortunately.

**Comment by davidpelaez** [comment]
@shawnsi this is a complicated unexpected situation because you have to choose wether you want to preserve the tag to query consul or wether the subdomain is to be handled by the app pointed at by the first subdomain. Consider a rails app that gives users subdomains (e.g. tumblr) for their account, this means that x.y.com is handled by the app in y.com so you must make the replacement so that the consul resolution points to y.com and not an instance of y.com with the tag x. This was the case for the initial system that I created this repo for, hence the replacement. Maybe you can send a PR with this being optinally turned off with a flag? This would allow the decision to lie on the side of the developer running the container. However, this would only make sense if this is used as an internal load balancer because from my perspective exposing the consul tags is slightly odd since it's a somewhat internal thing. But I don't know your environment, so please take my opinion with a grain of salt. What do you think?

**Comment by shawnsi** [comment]
@davidpelaez That makes more sense now.  I am using this as an internal load balancer as you suspected.  Considering srv-router is built with consul integration in mind it still seems unexpected to strip the tag component by default though.

I'll take a whack at implementing a configuration option to determine which upstream extraction logic to use.  In the meantime I can just use my fork to get the desired behavior for my infrastructure.

**Comment by davidpelaez** [comment]
I understand, please let me know if you manage to get a solution that can be merged. It's true that it was made for consul, but indeed it was made as the routing layer of an open source PaaS on a Consul cluster. Something like Deis for Consul, hence the inclination on the public side of the routing.

**Comment by davidpelaez** [comment]
I'll close this but if you have the code to be merged, please let me know and we can open it again or just send the PR directly.
